### ISSUE TITLE
Tiny sized gender chars

### ISSUE THREAD

**Issue by jojomi** [T-F-S/genealogytree#11]
First of all I have to say I love this package. Exhaustive documentation, beautiful output, high quality.

When I add birth **and** death dates for a person, the icons are suddenly very small. It works for birth only and also death only persons. Is there anything I can do to debug this further?

![genealogytree](https://user-images.githubusercontent.com/9872565/32636781-8b35c078-c5b6-11e7-9ab0-2de93da7cd10.png)

**Comment by T-F-S** [comment]
Without seeing code for the example, it is difficult to say what went wrong.

According to the picture,  the  icons for the third person (with birth and death dates), are moved outside the frame which is strange because there is much space left on the right hand side.

Generally, reserving more vertical space for the text should help, but I guess there is another problem which I cannot analyze without compilable code.

Also, you should check, if you have `tcolorbox` version 4.11 (or newer) on your system. If not, your should update this package, because it resolves some problems with tiny text parts which also affect `genealogytree`.

**Comment by jojomi** [comment]
Thank you for the quick answer and a hint to the right direction.

The key `level size=3.5cm` in `\begin{genealogypicture}`'s options was the culprit. I removed it since it did not change anything relevant in my case, so this is kind of fixed for me, you can close this issue if you think it is appropriate.

My system used `tcolorbox` 4.11 in a [docker container](https://github.com/jojomi/docker-latex-genealogytree) that I created to ship `genealogytree` without fuss.

**Comment by T-F-S** [comment]
I am glad that this was helpful. I will close the issue.
