### ISSUE TITLE
I am having trouble using lualatex with this package

### ISSUE THREAD

**Issue by jrtaylor-3** [T-F-S/genealogytree#14]
This snippet works fine with xelatex but not lualatex (current MikTeX distribution).   I have some other examples that do seem to work but this is a boiled down example of what my genealogy code generates.

\documentclass{standalone}
\usepackage[all]{genealogytree}

\begin{document}
	\gtrset{date format=yyyy.mm.dd}
	\begin{genealogypicture}
		[template=database portrait]
		child[id=F10]{
			g[id=I10]{ male, name=Bob } 
			p[id=I1]{ female, name=Carol } 
			child{ g[id=I11]{ male, name=Ted } }
			child{ g[id=I12]{ female, name=Alice } }
		}
	\end{genealogypicture}
\end{document}

[LuaLatexTestTree.log](https://github.com/T-F-S/genealogytree/files/1613208/LuaLatexTestTree.log)

**Comment by T-F-S** [comment]
It seems that lualatex stops working at all on my current maschine (I do not use it myself).
So, I cannot test your code in the moment. I will try on another maschine later.

**Comment by T-F-S** [comment]
`lualatex` is also completely broken on my second MikTeX installation. [Additionally, there are currently problems with the MikTeX repositories which are marked as outdated](https://tex.stackexchange.com/questions/409639/package-installation-outdated-repository) So, at the moment, I cannot update `lualatex` to test your example code.

**Comment by perstar** [comment]
This doesn't work because the standalone class doesn't work with lualatex. You can fix this with the luatex85 package. See answer to https://tex.stackexchange.com/questions/315025/lualatex-texlive-2016-standalone-undefined-control-sequence .

(Maybe there is some additional problem I don't know of; but this is the only problem I see with the example document, as tested with current texlive distribution.)

**Comment by jrtaylor-3** [comment]
perstar - That solved my problem!
