### ISSUE TITLE
Using the `database processor` outside a tree

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/genealogytree#24]
Hi

Say I want to create a number of "profiles" containing genealogical information, parsed and displayed according to the `genealogytree` options & styles — ie. symbols, date formatting, etc.

I have the following which does indeed print the names & birth data as expected, but before going further, I would love to know if there are any special considerations or precautions I should take :)

```latex
\documentclass{article}

\usepackage{genealogytree}

\newenvironment{genprofile}{%
}{%
	\gtrPrintDatabase%
}

\begin{document}

\begin{genprofile}
\gtrset{
	database/.cd,
	name = {Jens Hansen},
	birth = {1800}{Denmark},
}
\end{genprofile}

\begin{genprofile}
\gtrset{
	database/.cd,
	name = {Hans Jensen},
	birth = {1900}{Denmark},
}
\end{genprofile}

\end{document}
```

**Comment by T-F-S** [comment]
I think the main consideration is about avoiding to use internal macros as far as possible, because undocumented macros and options are in danger to be changed without warning.

Here,  `\gtrPrintDatabase` is undocumented, but needed for your application. Since using the database outside a tree seems a very reasonable application to me, I consider to document `\gtrPrintDatabase` officially to safeguard your approach. Currently, I do not have much time for such things, but I put it on my TODO list.

**Comment by mikkelee** [comment]
Thanks, there's no rush! I might post some observations & comments in this issue as I get deeper into my project.

**Comment by mikkelee** [comment]
~~An option for choosing to display the text values instead of the symbols themselves would be nice to have, ie. `\gtrset{birth/.initial=\gtr@sym@Born@text}`.~~

~~I can write up a patch to make each `\gtrsym...` macro express as text or symbol depending on a setting, if that is the correct approach.~~

e: this turns out not to be necessary for my usecase.

**Comment by T-F-S** [comment]
`\gtrPrintDatabase` is now officially documented (starting from version 1.32).
