### ISSUE TITLE
Support for Ibid.

### ISSUE THREAD

**Issue by wurfmaul** [T-F-S/genealogytree#45]
If the place of birth and death are the same, it is very common to write "[lbid.](https://en.wikipedia.org/wiki/Ibid.)" (or German "[ebd.](https://de.wikipedia.org/wiki/Ebenda)") for the second time instead. Unfortunately I could not achieve this in a nice way:

```
birth={1990-01-01}{Vienna},
death={2024-01-01}{lbid.},
```

The above would result in something like:

> † 1.1.2024 in lbid.

What I would like to get is this:

> † 1.1.2024 lbid.

Is there a way to remove the "in" in case the place is "lbid./ebd."? In the documentation I could not find a way to change the code of `/gtr/place`, unlike `/gtr/date code`, `/gtr/event code`, etc.

**Comment by perstar** [comment]
See https://tex.stackexchange.com/questions/690852/genealogytree-replace-identical-marriage-and-death-places-automatically-by-ibi for an example of how to get "ibid" automatically in those cases. In that example the "place text" is empty though.
One (admittedly ugly) workaround is to add "in " to the beginning of the place-names instead. That workaround can have some other merits depending on language, because sometimes you might want to use different prepositions for different kinds of places.

**Comment by wurfmaul** [comment]
Interesting approach, thank you @perstar!

I just put a similar idea in a more primitive work-around:

```tex
\gtrset{event code={\gtrPrintEventPrefix{#1}\,\gtrPrintDate{#1}\gtrifplacedefined{#1}{\ifcsstring{gtrDB#1place}{lbid.}{~lbid.}{~\gtrPrintPlace{#1}}}{}}}
```

**Comment by mikkelee** [comment]
Just for reference, I needed to skip the "in" for certain place names. My solution was to look for placenames that start with !, so I can write for example `!on an island` to skip it:
https://github.com/T-F-S/genealogytree/issues/10#issuecomment-326588749

**Comment by wurfmaul** [comment]
Very cool idea @mikkelee! It is also more flexible than my work-around! :clap:

**Comment by T-F-S** [comment]
I added a LaTeX3 variant of @mikkelee original patch, see https://github.com/T-F-S/genealogytree/issues/10#issuecomment-1994286361
It does the same, but `xstring` is not required.
